### ISSUE TITLE
F-34 Error en la medición de indicadores, en sin sexo de nacimiento es 0 y mujeres son 18 y hombres si esta bien son 12

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#34]
![COR1440-error](https://user-images.githubusercontent.com/10052756/98585932-fcb31b80-2295-11eb-89b6-77f3cc17e03e.jpeg)

**Comment by vtamara** [comment]
Parece que configuró mal la medición o cambio el tipo después de haberla agregado. Verifique que sea cuenta de personas.  Eliminela y vuelva a añadir.
