### ISSUE TITLE
F-42 Al pulsar Documentos y plantillas >> Plantillas para un registro en hoja de calculo >> Nueva genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#42]
![Captura de pantalla de 2021-01-13 07-42-49](https://user-images.githubusercontent.com/10052756/104453884-12cda880-5573-11eb-84dd-4b0a28fad8b1.png)

**Comment by vtamara** [comment]
Repetido #43
