### ISSUE TITLE
F-50 Al generar un reporte de proyecto genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#50]
![Captura de pantalla de 2021-02-14 19-05-47](https://user-images.githubusercontent.com/10052756/107893228-f9b07280-6ef7-11eb-87e6-ea583688f852.png)

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/cor1440_gen/commit/95d56681d27a77d77c47f969db626870bef88da3
