### ISSUE TITLE
F-56 Al hacer conteos por Conteo de beneficiarios por actividad de convenio y filtrar por sexo genera un comentario de error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#56]
![Captura de pantalla de 2021-04-12 17-25-07](https://user-images.githubusercontent.com/10052756/114470494-9b7cd480-9bb4-11eb-83ae-408cd10ad8eb.png)

**Comment by vtamara** [comment]
Resuelto.
