### ISSUE TITLE
F-57 Al elegir un Proyectos que le caracterizan en un formulario de beneficiario genera un comentario de error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#57]
![Captura de pantalla de 2021-04-12 17-36-39](https://user-images.githubusercontent.com/10052756/114471453-493cb300-9bb6-11eb-9fa7-4243bf7d9eeb.png)

**Comment by vtamara** [comment]
Resuelto.
