### ISSUE TITLE
R-59 Agregar validación en actividad cuando no se elija unidad de duración. 

### ISSUE THREAD

**Issue by alejocruzrcc** [pasosdeJesus/cor1440_gen#59]

**Comment by vtamara** [comment]
En cor1440 no hay campo duración.  Lo hay en cor1440_cinep y en cor1440_pdJ. 
En cor1440_cinep no presenta error, en cor1440_pdJ  presenta como unidad de duración en el resumen "Unidad de duración: ERROR-CON-[["Minutos", :I], ["Horas", :H], ["Días", :D], ["Meses", :M]]-Y- -FAVOR-REPORTAR".

Podría ser mejor no permitir en formulario que este campo esté en blanco sino que de manera predeterminada esté en Horas.

**Comment by vtamara** [comment]
En ambos se deja horas de manera predeterminada y sin opción de poner en blanco.

**Comment by vtamara** [comment]
(Sería mejor mover lo común a cor1440_gen y en cor1440_cinep cambiar mduración:varchar(50) por medduracion:varchar(1) como en cor1440_pdJ.
