### ISSUE TITLE
F-63 EN resumen de actividad al generar un  ods, xlsx o pdf no lo genera sino que se va a la pagina de inicio.

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#63]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-04-26 18-43-19](https://user-images.githubusercontent.com/10052756/116164467-54680680-a6bf-11eb-9693-f3dc0fb2192d.png)
![Captura de pantalla de 2021-04-26 18-43-30](https://user-images.githubusercontent.com/10052756/116164472-57fb8d80-a6bf-11eb-902f-465247ec022c.png)

**Comment by vtamara** [comment]
Solucionado.
