### ISSUE TITLE
F-80 Al colocar fecha en un formulario, y generar el ods de una actividad no aparecen las fechas. Y los campos enteros y flotantes se presentan como textos en la hoja de cálculo.

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#80]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-08 20-15-23](https://user-images.githubusercontent.com/10052756/121277556-7942c280-c896-11eb-893f-0a790ac12661.png)

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/mr519_gen/commit/9ffac18d50de1d3fec79a30a385c82e06c6dd6a2 y  
https://github.com/pasosdeJesus/heb412_gen/commit/583a28a9ed684a7be65a504632f3e450266d986b
