### ISSUE TITLE
F-81 En la tabla Región para un grupo no se puede crear una nueva porque genera error. "La ficha tiene 1 error. No pudo crear grupo en directorio LDAP: 50 - Insufficient Access Rights. Saltando creación en base de datos"

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_gen#82]
![Captura de pantalla de 2021-06-14 20-06-35](https://user-images.githubusercontent.com/10052756/121977829-80614900-cd4c-11eb-9445-71266706cc6b.png)

**Comment by vtamara** [comment]
Esto es para cor1440_cinep, no para este repositorio.

el título habla de Región para un grupo, pero el pantallazo es para Grupo.

Es normal que no permita crear un Grupo sin directorio LDAP.
